spring.http.converters.preferred-json-mapper: gson
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
axon:
  axonserver:
    enabled: false

axon.serializer.general: jackson
axon.serializer.events: jackson
axon.serializer.messages: jackson

jdbc:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres1234

elasticsearch:
  host: localhost
  port: 9300
